[workspace]
members = [
    "src/projects/*",
    "src/rustlings",
]
exclude = [
    "src/rustlings/dev",
    "src/rustlings/tests/test_exercises",
]
default-members = [
    "src/projects/*",
]
resolver = "2"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
