services:
  debian-trixie-slim:
    build:
      context: .
      dockerfile: Dockerfile.debian
      args:
        BASE_IMAGE: "debian"
        BASE_TAG: "trixie-slim"
    volumes:
      - ..:/home/${USER}/workspace/rust-book
    working_dir: /home/${USER}/workspace/rust-book
    restart: unless-stopped
    tty: true
